# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SnapKit'
pod 'SVProgressHUD'

#bug统计
pod 'Bugly', '~> 2.4.8'

target 'LPStatus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LPStatus

end
